# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
    alfresco:
        build:
          context: ./alfresco
          args:
            ALFRESCO_TAG: ${ALFRESCO_TAG}
        mem_limit: 2048m
        environment:
            JAVA_TOOL_OPTIONS: "
            -Dencryption.keystore.type=JCEKS
            -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
            -Dencryption.keyAlgorithm=DESede
            -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
            -Dmetadata-keystore.password=mp6yc0UD9e
            -Dmetadata-keystore.aliases=metadata
            -Dmetadata-keystore.metadata.password=oKIWzVdEdA
            -Dmetadata-keystore.metadata.algorithm=DESede
            "
            JAVA_OPTS: "
            -Delasticsearch.createIndexIfNotExists=true
            -Ddb.driver=org.postgresql.Driver
            -Ddb.username=alfresco
            -Ddb.password=alfresco
            -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
            -Dindex.subsystem.name=elasticsearch
            -Delasticsearch.host=elasticsearch
            -Delasticsearch.port=9200
            -Dshare.host=127.0.0.1
            -Dshare.port=8080
            -Dalfresco.host=localhost
            -Dalfresco.port=8080
            -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
            -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
            -Ddeployment.method=DOCKER_COMPOSE
            -Dtransform.service.enabled=true
            -Dtransform.service.url=http://transform-router:8095
            -Dsfs.url=http://shared-file-store:8099/
            -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
            -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/
            -Djodconverter.url=http://transform-core-aio:8090/
            -Dimg.url=http://transform-core-aio:8090/
            -Dtika.url=http://transform-core-aio:8090/
            -Dtransform.misc.url=http://transform-core-aio:8090/
            -Dcsrf.filter.enabled=false
            -Dalfresco.restApi.basicAuthScheme=true
            -DcontentPropertyRestrictions.enabled=false
            -Xms2048m -Xmx2048m
            "

    transform-router:
        image: quay.io/alfresco/alfresco-transform-router:${TRANSFORM_ROUTER_TAG}
        mem_limit: 512m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            CORE_AIO_URL: "http://transform-core-aio:8090"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8095:8095
        links:
            - activemq

    transform-core-aio:
        image: alfresco/alfresco-transform-core-aio:${TRANSFORM_CORE_AIO_TAG}
        mem_limit: 2048m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx1536m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8090:8090
        links:
            - activemq

    shared-file-store:
        image: alfresco/alfresco-shared-file-store:${SHARED_FILE_STORE_TAG}
        mem_limit: 512m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            scheduler.content.age.millis: 86400000
            scheduler.cleanup.interval: 86400000
        ports:
            - 8099:8099
        volumes:
            - shared-file-store-volume:/tmp/Alfresco/sfs

    # AWS Managed Service
    postgres:
        image: postgres:11.7
        mem_limit: 1024m
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5432:5432

    # AWS Managed Service
    activemq:
        image: alfresco/alfresco-activemq:5.15.8
        mem_limit: 1g
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP

    digital-workspace:
        image: quay.io/alfresco/alfresco-digital-workspace:latest
        mem_limit: 256m
        environment:
            BASEPATH: ./

    # HTTP proxy to provide HTTP Default port access to services
    proxy:
        image: angelborroy/acs-proxy:1.2.0
        mem_limit: 128m
        environment:
          - SHARE_ENABLED=false
          - SOLR_ENABLED=false
          - ACA_URL=http://digital-workspace:8080
        depends_on:
            - alfresco
        ports:
            - 8080:8080
        links:
            - digital-workspace
            - alfresco

    # AWS Managed Service
    elasticsearch:
        image: elasticsearch:7.10.1
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        ports:
            - 9200:9200
            - 9300:9300

    kibana:
        image: kibana:7.10.1
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch

    live-indexing-mediation:
        image: quay.io/alfresco/alfresco-elasticsearch-live-indexing-mediation:${LIVE_INDEXING_MEDIATION_TAG}
        depends_on:
            - elasticsearch
            - alfresco
        environment:
            SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
            SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616

    live-indexing-content:
        image: quay.io/alfresco/alfresco-elasticsearch-live-indexing-content:${LIVE_INDEXING_CONTENT_TAG}
        depends_on:
            - elasticsearch
            - alfresco
        environment:
            SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
            SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
            ALFRESCO_SHAREDFILESTORE_BASEURL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file/

    live-indexing-metadata:
        image: quay.io/alfresco/alfresco-elasticsearch-live-indexing-metadata:${LIVE_INDEXING_METADATA_TAG}
        depends_on:
            - elasticsearch
            - alfresco
        environment:
            SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
            SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616

volumes:
    shared-file-store-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs
